import type { Car } from "./types";
const now = "2026-07-10T18:30:00Z";
// Fixtures used exclusively by scoring.test.ts. Never loaded by the application.
export const testCars: Car[] = [
  {
    id: "corolla-2023-tarnow",
    title: "Corolla Touring Sports 1.8 HEV Comfort",
    year: 2023,
    power: 140,
    price: 92900,
    mileage: 59165,
    location: "Tarnów",
    distance: 480,
    trim: "Comfort",
    tech: false,
    heatedSeats: false,
    polishSalon: true,
    aso: true,
    oneOwner: false,
    noStructuralDamage: true,
    vat23: true,
    camera: true,
    ecvt: true,
    body: "Touring Sports",
    seller: "Toyota Kobos",
    vin: "SB1ZB3AE20E040424",
    firstSeen: "2026-07-08",
    verifiedAt: now,
    listings: [
      {
        source: "Toyota Pewne Auto",
        url: "https://pewneauto.pl/oferta/toyota-corolla/406431",
        price: 92900,
        active: true,
        checkedAt: now,
      },
    ],
    notes: [
      "Cena poniżej celu dla rocznika",
      "Daleki wyjazd — wymaga przewagi jakościowej",
    ],
  },
  {
    id: "corolla-2023-warszawa",
    title: "Corolla Touring Sports 1.8 HEV Comfort + Tech",
    year: 2023,
    power: 140,
    price: 98500,
    mileage: 31054,
    location: "Warszawa",
    distance: 310,
    trim: "Comfort + Tech",
    tech: true,
    heatedSeats: true,
    polishSalon: true,
    aso: true,
    oneOwner: true,
    noStructuralDamage: true,
    vat23: true,
    camera: true,
    ecvt: true,
    body: "Touring Sports",
    seller: "Toyota Warszawa Żerań",
    vin: "SB1ZB3AE00E079920",
    firstSeen: "2026-07-09",
    verifiedAt: now,
    listings: [
      {
        source: "Toyota Pewne Auto",
        url: "https://pewneauto.pl/oferta/toyota-corolla/362674",
        price: 98500,
        active: true,
        checkedAt: now,
      },
      {
        source: "OTOMOTO",
        url: "#",
        price: 96900,
        active: true,
        checkedAt: now,
      },
    ],
    notes: [
      "Bardzo dobre dopasowanie segmentu",
      "Różnica cen między portalami: 1 600 zł",
    ],
  },
  {
    id: "corolla-2022-poznan",
    title: "Corolla Touring Sports 1.8 Hybrid Comfort + Tech",
    year: 2022,
    power: 122,
    price: 89900,
    mileage: 72600,
    location: "Poznań",
    distance: 12,
    trim: "Comfort + Tech",
    tech: true,
    heatedSeats: true,
    polishSalon: true,
    aso: true,
    oneOwner: true,
    noStructuralDamage: true,
    vat23: true,
    camera: true,
    ecvt: true,
    body: "Touring Sports",
    seller: "Toyota Poznań",
    vin: "DEMO0000000000001",
    firstSeen: "2026-07-10",
    verifiedAt: now,
    listings: [
      {
        source: "Dealer Toyota",
        url: "#",
        price: 89900,
        active: true,
        checkedAt: now,
      },
    ],
    notes: ["Lokalna oferta demonstracyjna", "Pełne dopasowanie do celu 2022"],
  },
  {
    id: "corolla-2021-leszno",
    title: "Corolla Touring Sports 1.8 Hybrid Comfort",
    year: 2021,
    power: 122,
    price: 81900,
    mileage: 88400,
    location: "Leszno",
    distance: 82,
    trim: "Comfort",
    tech: false,
    heatedSeats: true,
    polishSalon: true,
    aso: true,
    oneOwner: false,
    noStructuralDamage: true,
    vat23: false,
    camera: true,
    ecvt: true,
    body: "Touring Sports",
    seller: "Auto Partner",
    vin: "DEMO0000000000002",
    firstSeen: "2026-07-07",
    verifiedAt: now,
    listings: [
      {
        source: "OTOMOTO",
        url: "#",
        price: 81900,
        active: true,
        checkedAt: now,
      },
    ],
    notes: [
      "Cena w docelowym przedziale",
      "Przebieg blisko górnej preferowanej granicy",
    ],
  },
];
