export type Listing = {
  source: string;
  url: string;
  price: number;
  year?: number;
  mileage?: number;
  power?: number;
  cashPrice?: number;
  active: boolean;
  checkedAt: string;
  description?: string;
  images?: string[];
  camera?: boolean;
  parkingSensors?: boolean;
  heatedSeats?: boolean;
  heatedWiperArea?: boolean;
  rainSensor?: boolean;
  autoDimmingMirror?: boolean;
  foldingMirrors?: boolean;
  lumbarAdjustment?: boolean;
  heatedSteeringWheel?: boolean;
  keyless?: boolean;
  wirelessCharging?: boolean;
  ics?: boolean;
  hybridHealthCheck?: boolean;
  toyotaWarranty?: boolean;
  polishSalon?: boolean;
  aso?: boolean;
  oneOwner?: boolean;
  noStructuralDamage?: boolean;
  vat23?: boolean;
  snapshotId?: string;
  reserved?: boolean;
  hybrid?: boolean;
  ecvt?: boolean;
};
export type Car = {
  id: string;
  title: string;
  year: number;
  power: number;
  price: number;
  cashPrice?: number;
  mileage: number;
  location: string;
  distance: number;
  trim: string;
  tech: boolean;
  heatedSeats: boolean;
  heatedWiperArea?: boolean;
  rainSensor?: boolean;
  autoDimmingMirror?: boolean;
  foldingMirrors?: boolean;
  lumbarAdjustment?: boolean;
  heatedSteeringWheel?: boolean;
  keyless?: boolean;
  wirelessCharging?: boolean;
  ics?: boolean;
  hybridHealthCheck?: boolean;
  toyotaWarranty?: boolean;
  reserved?: boolean;
  polishSalon: boolean;
  aso: boolean;
  oneOwner: boolean;
  noStructuralDamage: boolean;
  vat23: boolean;
  camera: boolean;
  parkingSensors?: boolean;
  ecvt: boolean;
  hybrid?: boolean;
  body: "Touring Sports";
  seller: string;
  vin?: string;
  firstSeen: string;
  verifiedAt: string;
  listings: Listing[];
  notes: string[];
  description?: string;
  images?: string[];
};
export type ScoreBreakdown = {
  deal: number;
  history: number;
  equipment: number;
  location: number;
  terms: number;
  total: number;
  confidence: number;
};
export type CodexJob = {
  id: string;
  url: string;
  source: string;
  title: string;
  status: "pending" | "processing" | "processed" | "failed";
  missing: string[];
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  error?: string;
  carId?: string;
  potentialScore: number;
  qualityScore: number;
  informationValue: number;
  potentialReasons: string[];
};
export type ScanRun = {
  id: string;
  trigger: "manual" | "automatic" | "cli";
  source?: string;
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  discovered: number;
  verified: number;
  rejected: number;
  errors: number;
};
export type MonitoringStats = {
  scheduled: boolean;
  intervalMinutes: number;
  runs: ScanRun[];
  snapshots?: number;
  snapshotBytes?: number;
};
