export type Listing = {
  source: string;
  url: string;
  price: number;
  year?: number;
  mileage?: number;
  power?: number;
  cashPrice?: number;
  active: boolean;
  missedScans?: number;
  inactiveAt?: string;
  checkedAt: string;
  description?: string;
  images?: string[];
  camera?: boolean;
  parkingSensors?: boolean;
  heatedSeats?: boolean;
  heatedWiperArea?: boolean;
  rainSensor?: boolean;
  autoDimmingMirror?: boolean;
  foldingMirrors?: boolean;
  lumbarAdjustment?: boolean;
  heatedSteeringWheel?: boolean;
  keyless?: boolean;
  wirelessCharging?: boolean;
  ics?: boolean;
  hybridHealthCheck?: boolean;
  toyotaWarranty?: boolean;
  polishSalon?: boolean;
  aso?: boolean;
  oneOwner?: boolean;
  noStructuralDamage?: boolean;
  vat23?: boolean;
  snapshotId?: string;
  reserved?: boolean;
  hybrid?: boolean;
  ecvt?: boolean;
  registrationNumber?: string;
  firstRegistrationDate?: string;
};
export type Car = {
  id: string;
  title: string;
  year: number;
  power: number;
  price: number;
  cashPrice?: number;
  mileage: number;
  location: string;
  distance: number;
  trim: string;
  tech: boolean;
  heatedSeats: boolean;
  heatedWiperArea?: boolean;
  rainSensor?: boolean;
  autoDimmingMirror?: boolean;
  foldingMirrors?: boolean;
  lumbarAdjustment?: boolean;
  heatedSteeringWheel?: boolean;
  keyless?: boolean;
  wirelessCharging?: boolean;
  ics?: boolean;
  hybridHealthCheck?: boolean;
  toyotaWarranty?: boolean;
  reserved?: boolean;
  polishSalon: boolean;
  aso: boolean;
  oneOwner: boolean;
  noStructuralDamage: boolean;
  vat23: boolean;
  camera: boolean;
  parkingSensors?: boolean;
  ecvt: boolean;
  hybrid?: boolean;
  body: "Touring Sports";
  seller: string;
  vin?: string;
  registrationNumber?: string;
  firstRegistrationDate?: string;
  cepik?: CepikReport;
  firstSeen: string;
  verifiedAt: string;
  listings: Listing[];
  notes: string[];
  description?: string;
  images?: string[];
};
export type CepikReport = {
  status: "pending" | "processing" | "ok" | "warning" | "failed";
  checkedAt?: string;
  error?: string;
  registrationStatus?: string;
  inspectionStatus?: string;
  insuranceStatus?: string;
  ownersTotal?: number;
  currentOwners?: number;
  coOwnersTotal?: number;
  timeline?: string[];
  rawSummary?: string;
};
export type ScoreBreakdown = {
  deal: number;
  history: number;
  equipment: number;
  location: number;
  terms: number;
  total: number;
  confidence: number;
};
export type CodexJob = {
  id: string;
  url: string;
  source: string;
  title: string;
  status: "pending" | "processing" | "processed" | "failed";
  missing: string[];
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  error?: string;
  carId?: string;
  potentialScore: number;
  qualityScore: number;
  informationValue: number;
  potentialReasons: string[];
};
export type ScanRun = {
  id: string;
  trigger: "manual" | "automatic" | "cli";
  source?: string;
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  discovered: number;
  verified: number;
  rejected: number;
  errors: number;
};
export type MonitoringStats = {
  scheduled: boolean;
  intervalMinutes: number;
  activeScan?: {
    trigger: "manual" | "automatic" | "cli";
    source?: string;
    startedAt: string;
  };
  runs: ScanRun[];
  snapshots?: number;
  snapshotBytes?: number;
  cepikRuns?: Array<{
    id: string;
    carId: string;
    offerUrl?: string;
    vin: string;
    registrationNumber: string;
    firstRegistrationDate: string;
    startedAt: string;
    finishedAt: string;
    durationMs: number;
    outcome: "success" | "warning" | "failed";
    error?: string;
    rawData?: unknown;
  }>;
};
